export const PROVIDER = {
  TENANT_CONNECTION: 'TENANT_CONNECTION',
  IDCARD_MODEL: 'IDCARD_MODEL',
  USER_MODEL: 'USER_MODEL',
  TENANT_MODEL: 'TENANT_MODEL',
  NEWS_MODEL: 'NEWS_MODEL',
  CIRCULAR_MODEL: 'CIRCULAR_MODEL',
  ELECTION_MODEL: 'ELECTION_MODEL',
  CANDIDATE_MODEL: 'CANDIDATE_MODEL',
  ELECTIONRESULT_MODEL: 'ELECTIONRESULT_MODEL',
  POLLING_UNIT: 'POLLING_UNIT',
};
